# Plugins
gems:
- jekyll-sitemap
safe: false
keep_files: ["img"]
# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Vietnam Android Academy"
email: "contact@vietandroid.academy"
description: "Vietnam Android Academy will be held on 3 cities of Vietnam: Hanoi, Danang, Ho Chi Minh."
baseurl: ""
url: "http://vietandroid.academy"
logo: "/img/seo/devfest.jpg"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "hungle90.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Infoy
organizerName: "GDG Hanoi"
organizerAlternateName: "Google Developer Group Hanoi"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "hung@gdghanoi.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdghanoi.org"

# Head
metaKeywords: "Android, Vietnam Android Academy, Da Nang, Ho Chi Minh, VR, CardBoard, google, programming, android, chrome, developers-"
twitterAccount: "@vietnamandroidacademy"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documentsi
c4pUrl: "http://bit.ly/vietnamandroidtrainers"
c4sponsorsUrl: "http://bit.ly/vietnamandroidtrainers"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/agenda/", text: "Agenda"}
 - {permalink: "/syllabus/", text: "Syllabus"}
 - {permalink: "/trainers/", text: "Trainer"}
 - {permalink: "/team/", text: "Team"}
 # - {permalink: "/logistics/", text: "Logistics"}



bottomNavigationLinks:
 - {link: "http://bit.ly/googleandroidcourse", text: "Đăng ký tại đây"}
rightNavigationButtons:
 - {link: "http://bit.ly/googleandroidcourse", text: "Đăng ký tại đây"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Vietnam Android Academy <typeout> "
eventDate: "December, 2015 "
typeoutTextValues: '"", "Hanoi", "Da Nang", "Ho Chi Minh", "Viet Nam"'
typeoutFallback: ""
heroButtons:
 - {link: "http://bit.ly/googleandroidcourse", text: "Registration"}
 - {link: "http://bit.ly/vietnamandroidtrainers", text: "For Trainer "}


# About Block
aboutTitle: "About Vietnam Android Academy"
aboutBlock:
 - {title: "Android", image: "conference.jpg", text: "The biggest Android Course that is supported by Google, Udacity and GDG community! " }
 - {title: "Workshops", image: "workshop.jpg", text: "Workshops, hands-on experience, hacking and debugging with Android device. " }
 - {title: "CodeLabs", image: "hackathon.jpg", text: "Learn to build Android App with Awesome speakers and lots of fun!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1000", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "30", specialCharacter: "+", info: "Trainer", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "cities", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Android Experts"
rockstarSpeakersButtonText: "See all experts"

# Location Block
locationBlockTitle: "Da Nang"
eventLocationName: "Saigon Tuorane Hotel"
eventLocationLink: "http://devfest.vn"
eventStreetAddress: "Saigon Tourane Hotel, No 5th, Dong Da st, Da Nang"
eventAddressLocality: "Da Nang"
eventAddressLocalityRegion: ""
eventPostalCode: "550000"
eventAddressCountry: "Vietnam"
eventStartTime: "2015-09-27T18:00"
eventDoorTime: "18:00"
eventEndTime: "2015-09-25T21:30"
eventPlaceCoordinates: "16.08293, 108.21962"
mapCenterCoordinates: "16.08293, 108.21962"
mapMobileCenterCoordinates: "16.08293, 108.21962"
# # Location Block
# locationBlockTitle: "Danang"
# eventLocationName: "VTC Academy"
# eventLocationLink: "http://devfest.vn"
# eventStreetAddress: "VTC Online building, No 18th, Tam Trinh, Hoang Mai"
# eventAddressLocality: "Danang"
# eventAddressLocalityRegion: ""
# eventPostalCode: "100000"
# eventAddressCountry: "Vietnam"
# eventStartTime: "2015-09-27T13:30"
# eventDoorTime: "13:00"
# eventEndTime: "2015-09-25T17:00"
# eventPlaceCoordinates: "20.99540, 105.86202"
# mapCenterCoordinates: "20.99540, 105.86202"
# mapMobileCenterCoordinates: "20.99540, 105.86202"
# # Location Block
# locationBlockTitle: "Ho Chi Minh"
# eventLocationName: "RMIT"
# eventLocationLink: "http://devfest.vn"
# eventStreetAddress: "VTC Online building, No 18th, Tam Trinh, Hoang Mai"
# eventAddressLocality: "Ho Chi Minh"
# eventAddressLocalityRegion: ""
# eventPostalCode: "100000"
# eventAddressCountry: "Vietnam"
# eventStartTime: "2015-09-27T13:30"
# eventDoorTime: "13:00"
# eventEndTime: "2015-09-25T17:00"
# eventPlaceCoordinates: "10.729502, 106.693618"
# mapCenterCoordinates: "10.729502, 106.693618"
# mapMobileCenterCoordinates: "10.729502, 106.693618"
# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "vietnamandroidacademy"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a trainer"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Registration"
ticketsInfo: "Tickets grant access to all sections, coffee brakes, lunch and party. All tickets are FREE for developers"
ticketsOffers:
 -
  name: "Workshop 1:05-06"
  price: "12/2015"
  priceCurrency: ""
  ticketsNumber: ""
  additionalInfo: ""
  ribbon: ""
  buyButtonLink: "http://bit.ly/googleandroidcourse"
  buyButtonText: "Registration"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-11-1T10:00"
  validThrough: "2015-12-1T10:00"
  # soldOut: true
  # soldOutText: "Closed"
 -
  name: "Workshop 2:12-13"
  price: "12/2015"
  priceCurrency: ""
  ticketsNumber: ""
  ribbon: ""
  additionalInfo: ""
  featured: true
  buyButtonLink: "http://bit.ly/googleandroidcourse"
  buyButtonText: "Registration"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-11-02T10:00"
  validThrough: "2015-12-01T10:00"

 -

  name: "Workshop 3:19-20"
  price: "12/2015"
  priceCurrency: ""
  ticketsNumber: ""
  buyButtonLink: "http://bit.ly/googleandroidcourse"
  buyButtonText: "Registration"
  additionalInfo: ""
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2015-09-02T10:00"
  validThrough: "2015-12-01T10:00"
 
  

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGHanoi", icon: "twitter"}
 - {link: "https://facebook.com/GDGHanoi", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdghanoi.org", text: "GDG Hanoi"}
   - {link: "http://gdgvietnam.org", text: "GDG VietNam"}
   - {link: "", text: "GDG Da Nang"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:contact@vietandroid.academy", text: "contact@vietandroid.academy"}
   - {link: "mailto:hanoi@vietandroid.academy", text: "hanoi@vietandroid.academy"}
   - {link: "mailto:danang@vietandroid.academy", text: "danang@vietandroid.academy"}
   - {link: "mailto:hcm@vietandroid.academy", text: "hcm@vietandroid.academy"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestvietnam"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "21.02867, 105.85215"
logisticsMapMobileCenterCoordinates: "21.02867, 105.85215"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Viet Nam"
directionDetailsCards:
 - {title: "Ha Noi", information: 'VTC Academy, The 4th Floor,VTC Online building, No 18th Tam Trinh, Hoang Mai, Hanoi.'}
 - {title: "Da Nang", information: 'SaiGonTour Ane Hotel, No 5th, Dong Da st, Da Nang'}
 - {title: "Ho Chi Minh City", information: 'RMIT University, 702 Nguyen Van Linh st, Tan Phong, Ho Chi Minh'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Syllabus"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Android for Beginner"
hackathonRows:
 - {title: "Lesson 1: Building Layouts", image: "hackathon-0.png", details: "<br><br>- Writing XML <br><br>- TextViews and Image Views<br><br>- Styling your views <br><br>- Positioning your views with ViewGroups<br><br>- LinearLayout weight<br><br>- Using RelativeLayout to position views relative to each other"}
 - {title: "Lesson 2: Making an App Interactive", image: "hackathon-1.png", details: "<br><br>- Making a button click execute code<br><br>- Having the app evaluate math expressions<br><br>- Declaring, initializing and using variables<br><br>- Variable scope<br><br>- Nested layouts<br><br>- The String datatype<br><br>- Combining Strings, ints and variables with concatenation "}
 - {title: "Lesson 3: Work with the Android Framework and Control Flow", image: "hackathon-2.png", details: "<br><br>- Method declaration and calling<br><br>- Parameters and return values<br><br>- An introduction to Object Oriented Programming<br><br>- Changing the attributes of your views dynamically<br><br>- Creating conditional logic using if/else statement"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
